### ISSUE TITLE
Can't set Manual Mode by changing temp in Home Assistant card

### ISSUE THREAD

**Issue by AnthonyKNorman** [fashberg/WThermostatBeca#101]
Firstly, thank you for a great implementation.
I flashed the device manually - BHT-002-GCLW
The Home assistant discovery was automatic. All good so far.
The operation seems to have a glitch.
If I hit the three little dots in the top right corner of the card and select manual under preset then all works as expected

```
{"idx":"Thermostat1",
"ip":"192.168.0.92",
"firmware":"1.18-fas",
"switchBackToAuto":true,
"temperature":22.50,
"targetTemperature":25.50,
"deviceOn":true,
"schedulesMode":"off",
"holdState":"manual",
"ecoMode":false,
"locked":false,
"systemMode":"heat",
"fanMode":"",
"mode":"heat",
"action":"heating",
"state":"heating",
"mcuId":"IAYz2WK1th0cMLmL1.0.0"}'
```
If, however, when in scheduler mode, I change the temperature on the front of the card. the card displays 'manual' but the LCD display still shows the clock symbol. In other words, it's still in scheduler mode.

```
{"idx":"Thermostat1",
"ip":"192.168.0.92",
"firmware":"1.18-fas",
"switchBackToAuto":true,
"temperature":22.00,
"targetTemperature":28.50,
"deviceOn":true,
"schedulesMode":"off",
"holdState":"manual",
"ecoMode":false,
"locked":false,
"systemMode":"heat",
"fanMode":"",
"mode":"heat",
"action":"heating",
"state":"heating",
"mcuId":"IAYz2WK1th0cMLmL1.0.0"}'
```

The MQTT seems to indicate it should be manual.
Do you know what is wrong?
Can I give you any more info?
Many thanks.

**Comment by AnthonyKNorman** [comment]
Further info. Changing the temperature makes the MQTT report manual mode, but this is not reflected in the LCD
![image](https://user-images.githubusercontent.com/19652957/104753632-2e41da80-5750-11eb-963c-d839422f4e04.png)

Calling the preset mode will set manual mode.
![image](https://user-images.githubusercontent.com/19652957/104753895-7f51ce80-5750-11eb-865f-7959dc8ada20.png)

**Comment by AnthonyKNorman** [comment]
I have managed to implement a fix for this by using an automation that sets 'scheduler' mode and then 'manual' mode when the climate.set_temperature service is called

```
- alias: 'climate.set_temperature call service'
  trigger:
  - platform: event
    event_type: call_service
    event_data: 
      domain: climate
      service: set_temperature
  action:
  - delay:
      seconds: 2
     
  - service: climate.set_preset_mode
    data_template:
      entity_id: climate.thermostat1
      preset_mode: scheduler
      
  - delay:
      seconds: 2
     
  - service: climate.set_preset_mode
    data_template:
      entity_id: climate.thermostat1
      preset_mode: manual

```
