### ISSUE TITLE
reboot via MQTT feature

### ISSUE THREAD

**Issue by mccasian** [fashberg/WThermostatBeca#120]
As Retain Messages on MQTT is in the same time a bless and a pain in the ass, I decided to reboot my Tasmota devices 30 seconds after Home Assistant starts via Automations->mqtt publish cmnd/device_name/restart. However, on wthermostatbeca seems that this feature does not work. I tried also therm/bedroom/cmnd/restart but still no luck.

It would be nice to add the reboot via MQTT feature

**Comment by paulius2k** [comment]
@mccasian - for me reboot of my BHT-002 via MQTT actually works.
This is the script I used:
```
reboot_moes_thermostat:
  alias: Reboot Moes Thermostat
  sequence:
  - service: mqtt.publish
    data:
      topic: "cmnd/therm/bathroom/restart"
      payload: "1"
  mode: single
```

**However**, after that I noticed strange behaviour when thermostat started rebooting periodically by itself.
Periods between reboots I witnessed: 30s, 45s, 60s, 1m30s, 2m40s.

MQTT Explorer did not show that the cmnd/restart message would be somehow repeated.

What solved this issue for me was restarting of HASS.
I still have no idea what exactly caused this behaviour.
