### ISSUE TITLE
Reduce Hyseresis via Automation in Home Assistant to less than 0.5°C

### ISSUE THREAD

**Issue by hakspiel** [fashberg/WThermostatBeca#192]
Hello,

i have created an Automation that will reduce the hysteresis to <0.5°C (less than +/- 0.25°C).

short explanation:
as soon as the room_temp is below the target_temp, the automation will increase the target temp by 1.5°C for 90mins, after 90mins target temp will be set back to the original value. 

Important is the delay of 90min for both commands. 
For my sluggish floorheating system 90min delay is perfect to prevent bouncing of the relay. 
the dead_time of the my floorheating system is also in the range of 90min, so there is nearly no effect on the room temp.

what you need:
- 1 additinal Sensor for target temperature

configuration of "Livingroom_target_temp" Sensor in configuration.yaml
```
mqtt:
  sensor:
    - name: "livingroom_target_temp"
      state_topic: "therm/wohn/stat/things/thermostat/properties"
      unit_of_measurement: '°C'
      value_template:  "{{ (value_json.targetTemperature)|float }}"
```

Automation.yaml:

````
- id: '1675003187748'
  alias: Livingroom Thermostat Hysteresis <0.5°C
  description: ''
  trigger:
  - platform: template
    value_template: '{{(states(''sensor.livingroom_therm_temperature'')|float) < (states(''sensor.livingroom_target_temp'')|float)}}'
  condition: []
  action:
  - service: climate.set_temperature
    data_template:
      temperature: '{{(states(''sensor.livingroom_target_temp'')|float  + 1.5)}}'
    target:
      device_id: e52f9c62b0eb70ebbd99f70afa2943df #replace with your Device ID
  - delay:
      hours: 1
      minutes: 30
      seconds: 0
      milliseconds: 0
  - service: climate.set_temperature
    data_template:
      temperature: '{{(states(''sensor.livingroom_target_temp'')|float  - 1.5)}}'
    target:
      device_id: e52f9c62b0eb70ebbd99f70afa2943df #replace with your Device ID
````
