### ISSUE TITLE
payload of True ignored

### ISSUE THREAD

**Issue by IanAdd** [fashberg/WThermostatBeca#25]
HA sends true and false payloads out capitalised. Capitalised True is not recognised by your software. false and False both work, however.

Enclosing them in quotes in the HA payload is a workaround but then the state_on has to be explicitly added to the entity as the default is to match to the payload and "true" does not match the returned state of true, ie without quotes.
The example below works
```
switch:
  - platform: mqtt
    unique_id: ensuite_auto_enable
    name: "Ensuite can revert to Auto"
    state_topic: "ensuite/stat/things/thermostat/properties"
    value_template: >
      {{ value_json.switchBackToAuto }}
    command_topic: "ensuite/cmnd/things/thermostat/properties/switchBackToAuto"
    payload_on: "true"
    payload_off: false
# state normally not required to be here as it defaults to following payload values.
# but needed here as payload_on cannot be sent unquoted but state is returned unquoted.!
    state_on: true
    optimistic: false
    qos: 0
    retain: true
```
