### ISSUE TITLE
What defines ecoMode Temp

### ISSUE THREAD

**Issue by IanAdd** [fashberg/WThermostatBeca#28]
When I switch on ecoMode the mqtt message still shows mode:heat and action:heating.
The lovelace climate card shows Heating-Away and the targetTemp changes to 20.

Can the climate card show Idle-Away if it is no longer heating, above currentTemp.
Can the ecomode target temp be user amended ?

I'd like to be able to set it to 5 for frost protection when house is empty, for example.

**Comment by fashberg** [comment]
Hey again @IanAdd ,

for heating-away / idle-away see #26 

The ecoTargetTemperature is set fixed to 20 degrees and can't be changed - this is written in the longer BHT-002-Manual:
 "Economy button: in this mode the temperature will be kept 20 degree. This temperature cannot be changed or adjusted"

See https://github.com/fashberg/WThermostatBeca/blob/master/docs/BHT-002-Manual-long.pdf

Because this is hardcoded in MCU it can't be changed.

I've thought that setting no 2, deadzone temperature is something like frost protection, but this controls the hysteresis (i've tested with some ice-buckets).

I'm not using ecoMode. In my HASS i'm using this automation to set all thermostates to 17 degrees and mode manual:

```yaml
- id: e786f88cddd343aa8bb4e4212d4754f9
  alias: AwayFromHome
  trigger:
  - entity_id: input_boolean.away
    platform: state
    to: 'on'
  action:
  - entity_id: all
    service: light.turn_off
  - data:
      hvac_mode: heat
    entity_id: all
    service: climate.set_hvac_mode
  - data:
      temperature: 17
    service: climate.set_temperature
  mode: single
```

Also in Off-State the WiFi Module is enabled so i case of currentTemperature of less than 5 degress you could switch the thermostate on with another automation.

Folke
