### ISSUE TITLE
Diffrent Current Temperature Sensor ?

### ISSUE THREAD

**Issue by bttfw** [fashberg/WThermostatBeca#70]
Is it possible to use a Home Assistant Sensor as the Current Temperature for the device?

I have multiple temp sensors around the house and I would like to use the avg temp of them as Current Temperature is this somehow possible

**Comment by bttfw** [comment]
No way to do that ?

**Comment by kocsishome** [comment]
Hello!

```
sensor:
  - platform: mqtt
    state_topic: 'home/room/stat/things/thermostat/properties/temperature'
    name: 'Bedroom Temperature'
    unit_of_measurement: '°C'
```
